config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users
  resources :planets do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show, :edit, :update, :destroy]
  # get 'reservations/new', to: 'reservations#new', as: :new_reservation
  # get '/reservations', to: 'reservations#show'
  # get 'reservations/:id/edit', to: 'reservations#edit', as: :edit_reservation
  resources :users do
    resources :reservations, only: [:index]
    resources :planets, only: [:edit]
  end


  get '/profile', to: "users#profile", as: :profile
  get '/profile/:planet_id/edit', to: "users#edit", as: :test_amine


  root 'planets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :reservations, dependent: :destroy
  belongs_to :user
  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :planet

  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :planets, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_one_attached :photo
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   skip_before_action :authenticate_user!, only:[:home, :show]
  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  def index
    @planets = Planet.all
     if params[:query].present?
      @planets = Planet.search_by_name_and_description(params[:query])

      # if @planets.empty?

      # else
      # @planets = Planet.search_by_name_and_description(params[:query])
      # end
    else
     @planets = Planet.all
    end
  end

  def show
    @reservation = Reservation.new

  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    @planet.save!
    redirect_to planets_path
  end

  def edit
  end

  def update
    @planet.update(planet_params)

    redirect_to planets_path(@planet)
  end

  def destroy
    @planet.destroy
    redirect_to profile_path
  end

  def planet_params
    params.require(:planet).permit(:name, :description, :price, photos: [])
  end

  def set_planet
    @planet = Planet.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
  end

  def new
    @planet = Planet.find(params[:planet_id])
    @reservation = Reservation.new
  end

  def edit
      @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation.update(reservation_params)

    redirect_to reservation_path(@reservation)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @planet = Planet.find(params[:planet_id])
    @reservation.planet = @planet
    @reservation.user = current_user

    if @reservation.save!
      redirect_to profile_path
    else
      render :new
    end
  end

  def show
    @reservations = Reservation.where(user: current_user)
  end

  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to profile_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @reservations = current_user.reservations
    @planets = current_user.planets
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <style>
    @import url('https://fonts.googleapis.com/css?family=Inconsolata|Krona+One&display=swap');
  </style>
  <title>PlanetWork</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %>
  <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>

    <%= yield %>


  <%= javascript_pack_tag 'application' %>
</body>

</html>

app/views/planets/edit.html.erb
<div class="container">
  <div>
    <h1>Edit a Planet</h1>
  </div>

  <div>
    <%= simple_form_for [@planet] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Save !", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/planets/index.html.erb
<div class="container">
<%= cl_video_tag("samples/12-5-vf-insta_lzoype", autoplay: true, muted: true, playsinline: true) %>
  <div class="row mb-4">
    <% @planets.each do |planet| %>
    <div class="col-12 col-sm-12 col-md-6 col-lg-4">
      <%= link_to planet_path(planet), class: "link_card"  do %>
      <div class="card-trip">
        <% planet.photos.first do |photo| %>
          <img src="<%= cl_image_path photo.key %>" />
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= planet.name %>
            </h2>
          </div>
          <h2 class="card-trip-pricing"><%= planet.price %>k€/j</h2>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/planets/new.html.erb
<div class="container">
  <div>
    <h1>Ajouter une planète</h1>
  </div>

  <div>
    <%= simple_form_for [@planet] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.file_field :photos, multiple: true, direct_upload: true %>
    <%= f.submit "Ajouter !", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/planets/show.html.erb
<div class="container">

<video playsinline="true" autoplay="autoplay" muted="muted" poster="https://res.cloudinary.com/dq5e0qdnx/video/upload/v1/samples/12-5-vf-insta_lzoype.jpg" src="https://res.cloudinary.com/dq5e0qdnx/video/upload/v1/samples/12-5-vf-insta_lzoype.mp4" type="video/mp4">aze</video>
<% @planet.photos.each do |photo| %>
<%= cl_video_tag("samples/12-5-vf-insta_lzoype", autoplay: true, muted: true, playsinline: true) %>

    <img src="<%= cl_image_path photo.key %>" />
  <% end %>
  <div class="planet-card">

    <div class="planet-card-info">
      <div>
        <div>
          <h1><%= @planet.name %>
          </h1>
          <p><%= @planet.description %></p>
        </div>
        <h2 class="planet-card-pricing"><%= @planet.price %>k€/j</h2>
      </div>
      <div class="owner-info">
        <h3>Propriétaire&nbsp;:</h3>
        <% if @planet.user.photo.attached? %>
        <%= cl_image_tag @planet.user.photo.key, width: 40, height: 40, crop: :fill, alt: "alttext", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% else %>
        <%= image_tag "astronaut.png", alt: "alttext", class: "avatar dropdown-toggle mb-1", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% end %>
        <p><%= @planet.user.email %></p>

      </div>
    </div>
  </div>

<%= render 'shared/new-reservation' %>



</div>


<!-- <div class="container-fluid" id="img">

  <div class="card text-center" style="width: 18rem;background-color: #D3D3D3;">
    <img class="card-img-top">
    <div class="card-body">
      <h5 class="card-title"><%= @planet.name %></h5>

      <p class="card-text"><%= @planet.description %></p>
      <p>Prix <%= @planet.price %>$</p>

      <%= link_to "Reservation", new_planet_reservation_path(@planet), class: "btn btn-light"%>
    </div>
  </div>
</div> -->

app/views/reservations/edit.html.erb
<h1>Edit your Reservation</h1>

<%= simple_form_for @reservations do |f| %>
  <%= f.error_notification %>
  <%= f.input :date %>
  <%= f.button :submit, class: "btn-dark" %>
<% end %>

app/views/reservations/new.html.erb
<div class="banner">
    <div class="d-flex justify-content-center">
  <h1 id="title-profile">Create your Reservation</h1>
</div>

<div class="d-flex flex-column bd-highlight mb-3">
<%= simple_form_for([ @planet, @reservation ])do |f| %>
  <%= f.error_notification %>
  <%= f.input :date%>
  <div class="d-flex justify-content-center">
  <%= f.button :submit, class: "btn-dark" %>
  </div>
<% end %>
</div>
</div>

<h2>Fuyez le Corona-Virus une bonne fois pour toute !</h2>

app/views/reservations/show.html.erb
<%if @reservations.count < 1 %>
  <div class ="d-flex justify-content-center mt-5">
    <p>Vous n avez aucunes reservations</p>
  </div>
  <%= link_to "Retour à la page d acceuil", root_path %>

<%else%>

  <%current_user.reservations.each do |reservation| %>
    <li>
       <strong><%= reservation.planet.name %></strong> est réservée pour le <%= reservation.date %>
    </li>
   <% end %>

<%end%>

app/views/reservations/user_show.html.erb
<%if @reservations.count < 1 %>
<div class ="d-flex justify-content-center mt-5">
<p>Vous n avez aucunes reservations</p>
</div>
<%= link_to "Retour a a la page d acceuil", root_path %>

<%else%>

<h1> <%@reservations.each do |reservation| %></h1>


<%= reservation%>

<%end%>

<%end%>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1 style="font-family: Krona One;">PlanetWork</h1>
    <p>Lassés des vacances en Crète ? Visitez plutôt une nouvelle <strong>planète</strong> !</p>
    <div class="row mb-4" style="display: flex; justify-content: space-evenly;">
      <div class="search-bar col-6 mt-4">
        <%= form_tag planets_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Chercher une planète ..."
      %>
      <div class="search-btn">
        <%= submit_tag "Go !", class: "search-button btn btn-dark" %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "planet1.svg", class: "white-logo" %>
    <% end %>

    <h2 style="font-family: Krona one; font-size: 20px; padding-top: 20px;">PlanetWork</h2>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Accueil", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, alt: "alttext", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= image_tag "astronaut.png", alt: "alttext", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new-reservation.html.erb
<div class="bann">
  <div class="d-flex justify-content-center">
    <h2 id="title-profile">Réservez dès maintenant :</h2>
  </div>

  <div class="d-flex flex-column bd-highlight">
    <%= simple_form_for([ @planet, @reservation ])do |f| %>
    <%= f.error_notification %>
    <%= f.input :date%>
    <div class="d-flex justify-content-center mb-4">
      <%= f.button :submit, 'Réserver !', class: "btn-dark" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="containeur0">
  <div class="profile-card">
    <h1 class="title-profile">Mon profil</h1>
    <% if current_user.photo.attached? %>
    <div>
      <%= cl_image_tag current_user.photo.key, width: 200, height: 200, crop: :fill %>
    </div>
    <% else %>
    <div>
      <%= image_tag "astronaut.png", width: 200, height: 200, crop: :fill %>
    </div>
    <% end %>
    <p class="mt-2">Email: <%= current_user.email %></p>
    <%= link_to "Mettre à jour le profil", edit_user_path(current_user) %> <br>
    <%= link_to "Ajouter une planete", new_planet_path, class: "btn btn-dark mt-4" %>
  </div>
  <div class="containeur1">
    <div class="containeur2">
      <h2 class="title-profile">Mes réservations</h2>
      <div class="row">
        <% @reservations.each do |reservation| %>
        <div class="myreservations col-12 col-sm-12 col-md-4 col-lg-4">
          <div class="card-trip">
           <% reservation.planet.photos.each do |photo| %> 
            <img src="<%= cl_image_path photo.key if reservation.planet.photos.attached? %>" />
            <% end %>
            <div class="card-trip-infos" style="color: black;">
              <div>
                <h2><%= reservation.planet.name %>
                </h2>
                <p>Réservé le : <%= reservation.date %></p>
                <%= link_to "", reservation_path(reservation),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "fas fa-trash" %>
              </div>
              <h2 class="card-trip-pricing"><%= reservation.planet.price %>€</h2>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="containeur3">
      <h2 class="title-profile">Mes planètes</h2>
      <div class="row">
        <% @planets.each do |planet| %>
        <div class="myplanets col-12 col-sm-12 col-md-4 col-lg-4">
          <div class="card-trip">
          <% planet.photos.each do |photo| %>
            <img
            src="<%= cl_image_path photo.key %>" />
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2 style="color: black;">
                <%= planet.name %>
                </h2>
                <%= link_to "", planet_path(planet),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "fas fa-trash" %>
                <%=link_to "", edit_planet_path(planet),
                class: "fas fa-pen" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>